---
title: "Solução Lista 01"
author: |
        | Nome: Luiz Lima Cezario
        | E-mail: luiz.cezario@aluno.ufabc.edu.br
        | (Não é preciso informar os RAs)
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r setup, include=TRUE, echo=FALSE}
options(tinytex.verbose = TRUE)
knitr::opts_chunk$set(echo = T,
                      fig.align='center',
                      cache=TRUE,
                      out.width = "60%",
                      out.heigth = "60%",
                      warning=FALSE,
                      message=FALSE)
options(width =70)
```

## Exercício 01
```{r echo = FALSE}
A = matrix(c(12,-1,-5,0,-1,7,2,-1,-5,2,10,1,0,-1,1,3),byrow = FALSE,nrow=4)
b = c(1,2,3,4)
print(solve(A,b))
```

## Exercício 02

```{r echo = FALSE}

Sylveres <- function(mt){
  sizes = nrow(mt)
  for(i in 1:sizes)
  {
    sub <- matrix(mt[1:i,1:i], nrow = i, byrow = FALSE)
    if(det(sub) < 0)
      return(FALSE)
  }
  return (TRUE)
}

print(Sylveres(A))
```

## Exercício 03
```{r echo = FALSE}
library(ggplot2) 
library(tibble)

numeros <- c(runif(100, -2 * pi, 2*pi))
numeros <- sort(numeros)
matriz <- tibble(cosenos = c(cos(numeros)),
                senos = c(sin(numeros)))
 ggplot(matriz, aes(x = numeros)) + geom_line(aes(y = cosenos, color = "cosenos", )) + geom_line(aes(y = senos, color="senos")) + 
   labs(title = "Cossenos e Senos") + ylab("cossenos e senos")

```

## Exercício 04
```{r echo=FALSE}
# Neste exercício, queremos fazer um gráfico do número de condicionamento de A a
# medida que aumentamos os elementos de sua diagonal.
set.seed(1)
Xf = matrix(runif(100,-1,1),nrow=10)
Af = t(Xf) %*% Xf

final <- tibble(x = c(seq(0, 99, 1)), condicionamento = c(seq(0, 99, 1)))
for(i in 1:nrow(final)){
  final$condicionamento[i] <- kappa(Af + i*diag(10))
}
ggplot(final, aes(x = x, y = condicionamento)) + geom_point() + labs(title = "condicionamento")

```